add: blossom zip

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -58,7 +58,7 @@ mount_apex() {
   setup_mountpoint /apex;
   mount -t tmpfs tmpfs /apex -o mode=755 && touch /apex/apextmp;
   shcon=$(cat /proc/self/attr/current);
-  echo "u:r:su:s0" > /proc/self/attr/current; # work around LOS Recovery not allowing loop mounts in recovery context
+  echo "u:r:su:s0" > /proc/self/attr/current 2>/dev/null; # work around LOS Recovery not allowing loop mounts in recovery context
   minorx=1;
   [ -e /dev/block/loop1 ] && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }');
   num=0;
@@ -94,7 +94,7 @@ mount_apex() {
       *) mount -o bind $apex $dest && echo "$dest (bind)" >&2;;
     esac;
   done;
-  echo "$shcon" > /proc/self/attr/current;
+  echo "$shcon" > /proc/self/attr/current 2>/dev/null;
   for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
     eval OLD_${var}=\$$var;
   done;
@@ -292,7 +292,7 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
+  # ui_print "Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
@@ -300,14 +300,14 @@ do_devicecheck() {
   for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        # ui_print "$testname" " ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort " " "unsupported device, aborting...";
   fi;
 }
 int2ver() {
@@ -346,151 +346,6 @@ do_versioncheck() {
     abort " " "Unsupported Android version. Aborting...";
   fi;
 }
-do_levelcheck() {
-  [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
-  local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "Checking Android security patch level...";
-  supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | grep -oE '[0-9]{4}-[0-9]{2}|-');
-  android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
-  parsed_lvl=$(echo $android_lvl | grep -oE '[0-9]{4}-[0-9]{2}');
-  if echo $supported_lvl | grep -q '^\-'; then
-    lo_lvl=0000-00;
-    hi_lvl=$(echo $supported_lvl | awk '{ print $2 }');
-  elif echo $supported_lvl | grep -q ' - '; then
-    lo_lvl=$(echo $supported_lvl | awk '{ print $1 }');
-    hi_lvl=$(echo $supported_lvl | awk '{ print $3 }');
-  elif echo $supported_lvl | grep -q '\-$'; then
-    lo_lvl=$(echo $supported_lvl | awk '{ print $1 }');
-    hi_lvl=9999-99;
-  fi;
-  if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | sort -g | grep -n "$parsed_lvl" | grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
-  else
-    abort " " "Unsupported Android security patch level. Aborting...";
-  fi;
-}
-dump_moduleinfo() {
-cat <<EOF > $1;
-id=ak3-helper
-name=AK3 Helper Module
-version=$(awk '{ print $3 }' $AKHOME/vertmp) $(grep -oE '#.[0-9]' $AKHOME/vertmp)
-versionCode=1
-author=AnyKernel3
-description=$KERNEL_STRING
-EOF
-}
-dump_moduleremover() {
-cat <<'EOF' > $1;
-#!/system/bin/sh
-MODDIR=${0%/*};
-if [ "$(cat /proc/version)" != "$(cat $MODDIR/version)" ]; then
-  rm -rf $MODDIR;
-  exit;
-fi;
-rm -f $MODDIR/update;
-. $MODDIR/post-fs-data.2.sh;
-EOF
-}
-do_modules() {
-  [ "$(file_getprop anykernel.sh do.modules)" == 1 ] || return 1;
-  local block modcon moddir modtarget module slot umask umountksu;
-  if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
-    if [ ! -d /data/adb -o ! -d /data/data/android ]; then
-      ui_print " " "Warning: No /data access for kernel helper systemless module!";
-      return 1;
-    fi;
-    cd $AKHOME/modules;
-    ui_print " " "Creating kernel helper systemless module...";
-    if [ -d /data/adb/magisk -a -f $AKHOME/magisk_patched ] || [ -d /data/data/me.weishu.kernelsu -a -f $AKHOME/kernelsu_patched ]; then
-      umask=$(umask);
-      moddir=/data/adb/modules/ak3-helper;
-      # this may be the initial KernelSU install or first module so setup as needed
-      if [ -f $AKHOME/kernelsu_patched ]; then
-        umask 077;
-        if [ ! -d /data/adb/modules ]; then
-          mkdir -p /data/adb/modules;
-          chmod 777 /data/adb/modules;
-        fi;
-        [ -d /data/adb/modules_update ] || mkdir -p /data/adb/modules_update;
-        [ -d /data/adb/ksu ] || mkdir -p /data/adb/ksu;
-        [ -f /data/adb/ksu/modules.img ] && cp -f /data/adb/ksu/modules.img /data/adb/ksu/modules_update.img;
-        if [ ! -f /data/adb/ksu/modules_update.img ]; then
-          /system/bin/make_ext4fs -b 1024 -l 256M /data/adb/ksu/modules_update.img 2>/dev/null \
-            || /system/bin/mke2fs -b 1024 -t ext4 /data/adb/ksu/modules_update.img 256M;
-        fi;
-        mount -t ext4 -o rw /data/adb/ksu/modules_update.img /data/adb/modules_update && umountksu=1;
-        touch /data/adb/ksu/update;
-        umask 022;
-        rm -rf $moddir;
-        mkdir -p $moddir;
-        dump_moduleinfo $moddir/module.prop;
-        touch $moddir/update;
-        moddir=/data/adb/modules_update/ak3-helper;
-      fi;
-      umask 022;
-      rm -rf $moddir;
-      mkdir -p system $moddir;
-      (mv -f product system;
-      mv -f vendor system;
-      mv -f system_ext system;
-      mv -f post-fs-data.sh post-fs-data.2.sh) 2>/dev/null;
-      cp -rLf * $moddir;
-      dump_moduleinfo $moddir/module.prop;
-      dump_moduleremover $moddir/post-fs-data.sh;
-      cp -f $AKHOME/vertmp $moddir/version;
-      touch $moddir/update;
-      umask $umask;
-      chcon -hR "u:object_r:system_file:s0" $moddir;
-      [ "$umountksu" ] && umount /data/adb/modules_update;
-    else
-      ui_print "Magisk/KernelSU installation not found. Skipped!";
-    fi;
-  else
-    cd $AKHOME/modules;
-    ui_print " " "Pushing modules...";
-    if [ -d /dev/block/mapper ]; then
-      for block in system vendor product; do
-        for slot in "" _a _b; do
-          blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null;
-        done;
-      done;
-    fi;
-    if [ ! -d /postinstall/tmp ]; then
-      mount -o rw,remount -t auto /system;
-      (mount -o rw,remount -t auto /vendor;
-      mount -o rw,remount -t auto /product) 2>/dev/null;
-    fi;
-    for module in $(find . -name '*.ko'); do
-      modtarget=$POSTINSTALL$(echo $module | cut -c2-);
-      if [ ! -e $modtarget ]; then
-        case $module in
-          */vendor/*) modcon=vendor;;
-          */product/*) modcon=product;;
-          *) modcon=system;;
-        esac;
-      fi;
-      if is_mounted $modtarget; then
-        mount -o rw,remount -t auto $modtarget;
-      fi;
-      mkdir -p $(dirname $modtarget);
-      cp -rLf $module $modtarget;
-      chown 0:0 $modtarget;
-      chmod 644 $modtarget;
-      if [ "$modcon" ]; then
-        chcon "u:object_r:${modcon}_file:s0" $modtarget;
-      fi;
-      if is_mounted $modtarget; then
-        mount -o ro,remount -t auto $modtarget;
-      fi;
-    done;
-    if [ ! -d /postinstall/tmp ]; then
-      mount -o ro,remount -t auto /system;
-      (mount -o ro,remount -t auto /vendor;
-      mount -o ro,remount -t auto /product) 2>/dev/null;
-    fi;
-  fi;
-  cd $AKHOME;
-}
 
 show_progress 1.34 25;
 ui_print " ";
@@ -506,11 +361,10 @@ if [ $? != 0 -o -z "$(ls bin)" ]; then
   abort "Busybox setup failed. Aborting...";
 fi;
 OLD_PATH="$PATH";
-export PATH="$AKHOME/bin:$AKHOME/tools:$PATH";
+export PATH="$AKHOME/tools:$AKHOME/bin:$PATH";
 
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " " " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
@@ -520,17 +374,16 @@ if [ -f version ]; then
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " ";
-grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
+ui_print " " "AnyKernel3 by osm0sis @ xda-developers";
+# grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
 ui_print " ";
 
 setup_env;
 
 do_devicecheck;
-do_versioncheck;
-do_levelcheck;
+#do_versioncheck;
 
-ui_print "Installing...";
+ui_print "installing...";
 # hack to maintain support for anykernel.sh files that weren't updated correctly along with the AK core
 CORE=$(grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
@@ -539,16 +392,13 @@ if [ $? != 0 ]; then
   abort;
 fi;
 
-do_modules;
-
-debugging;
-ui_print " ";
+#debugging;
 restore_env;
 
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " "Done!";
+ui_print " " "done!" " ";
 export PATH="$OLD_PATH";
 unset OLD_PATH OUTFD ZIPFILE;
